name: GitHub context

on:
  workflow_dispatch
jobs:
  github_context:
    runs-on: ubuntu-latest
    steps:
      - name: Github Info
        run: |
          echo 'Repository details ${{github.repository}}'
          echo 'Repo id ${{repository_id}}'
          echo 'Repo owner ${{repository_owner}}'
          echo 'Repo url ${{repositoryUrl}}'
          echo 'Repo rentention days ${{retention_days}}'
          echo 'Repo token ${{token}}'
          echo 'workflow ${{workflow}}'
