name: Auto-label PRs
permissions:
  pull-requests: write
on:
  pull_request:
    types: [opened]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Add label if PR author is repo owner
        if: github.actor == 'deepa081995'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: owner-pr

      - name: Add label for external contributors
        if: github.actor != 'deepa081995'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: external-contributor
